# Twitter API v2
#
# Twitter API v2 available endpoints
#
# The version of the OpenAPI document: 2.54
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.0
#

$:.push File.expand_path('../lib', __FILE__)
require 'twitter_client/version'

Gem::Specification.new do |s|
  s.name        = 'twitter_client'
  s.version     = TwitterClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['Anton Kozik']
  s.email       = ['pazitron@gmail.com']
  s.homepage    = 'https://openapi-generator.tech'
  s.summary     = 'Twitter API v2 Ruby Gem'
  s.description = 'Twitter API v2 available endpoints'
  s.license     = 'MIT'
  s.required_ruby_version = '>= 3.1'

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.executables   = []
  s.require_paths = ['lib']
  s.metadata['rubygems_mfa_required'] = 'true'
end
