=begin
#Twitter API v2

#Twitter API v2 available endpoints

The version of the OpenAPI document: 2.54

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'date'
require 'time'

module TwitterClient
  class ComplianceJobType
    TWEETS = "tweets".freeze
    USERS = "users".freeze

    def self.all_vars
      @all_vars ||= [TWEETS, USERS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ComplianceJobType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ComplianceJobType"
    end
  end
end
