=begin
#Twitter API v2

#Twitter API v2 available endpoints

The version of the OpenAPI document: 2.54

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TwitterClient::BlockUserRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TwitterClient::BlockUserRequest do
  let(:instance) { TwitterClient::BlockUserRequest.new }

  describe 'test an instance of BlockUserRequest' do
    it 'should create an instance of BlockUserRequest' do
      expect(instance).to be_instance_of(TwitterClient::BlockUserRequest)
    end
  end
  describe 'test attribute "target_user_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
