=begin
#Twitter API v2

#Twitter API v2 available endpoints

The version of the OpenAPI document: 2.54

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TwitterClient::InvalidRequestProblemAllOfErrors
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TwitterClient::InvalidRequestProblemAllOfErrors do
  let(:instance) { TwitterClient::InvalidRequestProblemAllOfErrors.new }

  describe 'test an instance of InvalidRequestProblemAllOfErrors' do
    it 'should create an instance of InvalidRequestProblemAllOfErrors' do
      expect(instance).to be_instance_of(TwitterClient::InvalidRequestProblemAllOfErrors)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "parameters"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
