=begin
#Twitter API v2

#Twitter API v2 available endpoints

The version of the OpenAPI document: 2.54

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TwitterClient::ListPinnedRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TwitterClient::ListPinnedRequest do
  let(:instance) { TwitterClient::ListPinnedRequest.new }

  describe 'test an instance of ListPinnedRequest' do
    it 'should create an instance of ListPinnedRequest' do
      expect(instance).to be_instance_of(TwitterClient::ListPinnedRequest)
    end
  end
  describe 'test attribute "list_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
