=begin
#Twitter API v2

#Twitter API v2 available endpoints

The version of the OpenAPI document: 2.54

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TwitterClient::NonCompliantRulesProblem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TwitterClient::NonCompliantRulesProblem do
  let(:instance) { TwitterClient::NonCompliantRulesProblem.new }

  describe 'test an instance of NonCompliantRulesProblem' do
    it 'should create an instance of NonCompliantRulesProblem' do
      expect(instance).to be_instance_of(TwitterClient::NonCompliantRulesProblem)
    end
  end
end
