=begin
#Twitter API v2

#Twitter API v2 available endpoints

The version of the OpenAPI document: 2.54

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TwitterClient::TweetCreateRequestMedia
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TwitterClient::TweetCreateRequestMedia do
  let(:instance) { TwitterClient::TweetCreateRequestMedia.new }

  describe 'test an instance of TweetCreateRequestMedia' do
    it 'should create an instance of TweetCreateRequestMedia' do
      expect(instance).to be_instance_of(TwitterClient::TweetCreateRequestMedia)
    end
  end
  describe 'test attribute "media_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tagged_user_ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
