=begin
#Twitter API v2

#Twitter API v2 available endpoints

The version of the OpenAPI document: 2.54

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TwitterClient::UserScrubGeoObjectSchema
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TwitterClient::UserScrubGeoObjectSchema do
  let(:instance) { TwitterClient::UserScrubGeoObjectSchema.new }

  describe 'test an instance of UserScrubGeoObjectSchema' do
    it 'should create an instance of UserScrubGeoObjectSchema' do
      expect(instance).to be_instance_of(TwitterClient::UserScrubGeoObjectSchema)
    end
  end
  describe 'test attribute "event_at"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "up_to_tweet_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "user"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
